security:
    # Configuration des encodeurs de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    # Configuration des fournisseurs d'utilisateur
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login                         
                username_parameter: _email
                password_parameter: _password
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login

    # Configuration des rôles hiérarchiques
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_DRTM, ROLE_EDBM, ROLE_DAT, ROLE_DG, ROLE_SG, ROLE_MINISTRE, ROLE_DNQ]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    # Contrôle d'accès
    access_control:
        - { path: ^/drtm-area, roles: ROLE_DRTM }
        - { path: ^/edbm-area, roles: ROLE_EDBM }
        - { path: ^/dat-area, roles: ROLE_DAT }
        - { path: ^/dg-area, roles: ROLE_DG }
        - { path: ^/sg-area, roles: ROLE_SG }
        - { path: ^/ministre-area, roles: ROLE_MINISTRE }
        - { path: ^/dnq-area, roles: ROLE_DNQ }
        - { path: ^/super-admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
