<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241126135407 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activite1 (id INT AUTO_INCREMENT NOT NULL, groupe_activite1_id INT NOT NULL, nom VARCHAR(255) NOT NULL, INDEX IDX_EEB97E0916C293C5 (groupe_activite1_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `admin` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_880E0D76E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE apropos (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) NOT NULL, contenu LONGTEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cas_de_location (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, nom_bailleur VARCHAR(255) NOT NULL, adresse_bailleur VARCHAR(255) NOT NULL, nom_preneur VARCHAR(255) NOT NULL, adresse_de_preneur VARCHAR(255) NOT NULL, duree_bailleur INT NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, nom_du_signateur VARCHAR(255) NOT NULL, date_du_signateur DATE NOT NULL, signataire VARCHAR(255) NOT NULL, INDEX IDX_9D07659EA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categorie_classement (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, ravinala_selection VARCHAR(255) NOT NULL, etoile_selection VARCHAR(255) NOT NULL, INDEX IDX_CB2757C1A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commune (id INT AUTO_INCREMENT NOT NULL, district_id INT NOT NULL, name VARCHAR(100) NOT NULL, INDEX IDX_E2E2D1EEB08FA272 (district_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE demande (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, texte VARCHAR(500) NOT NULL, INDEX IDX_2694D7A5A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_camping (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_62841159A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_camping_detail (id INT AUTO_INCREMENT NOT NULL, description_camping_id INT NOT NULL, designation VARCHAR(255) NOT NULL, superficie VARCHAR(255) DEFAULT NULL, nombre INT DEFAULT NULL, INDEX IDX_7CBBCC90BC20B444 (description_camping_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_equipement_restaurant (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_F3FB103BA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_equipement_restaurant_detail (id INT AUTO_INCREMENT NOT NULL, description_restaurant_id INT NOT NULL, designation VARCHAR(255) NOT NULL, nombre INT DEFAULT NULL, INDEX IDX_D5B0B326464F712D (description_restaurant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_hebergement (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_A48EC36DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_hebergement_detail (id INT AUTO_INCREMENT NOT NULL, description_hebergement_id INT NOT NULL, designation VARCHAR(255) NOT NULL, superficie VARCHAR(255) DEFAULT NULL, nombre INT DEFAULT NULL, INDEX IDX_66F7598ECC99B74D (description_hebergement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_camping (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_3CBFF80CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_camping_detail (id INT AUTO_INCREMENT NOT NULL, description_question_camping_id INT NOT NULL, designation VARCHAR(255) NOT NULL, reponse VARCHAR(500) DEFAULT NULL, INDEX IDX_C13EB1CCE8E0F9C0 (description_question_camping_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_choix_camping (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_6852BD2EA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_choix_camping_detail (id INT AUTO_INCREMENT NOT NULL, description_question_choix_camping_id INT NOT NULL, designation VARCHAR(255) NOT NULL, reponse VARCHAR(500) DEFAULT NULL, INDEX IDX_52A2993D809C4E9F (description_question_choix_camping_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_choix_hebergement (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_B5B374CBA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_choix_hebergement_detail (id INT AUTO_INCREMENT NOT NULL, description_question_choix_hebergement_id INT NOT NULL, designation VARCHAR(255) NOT NULL, reponse VARCHAR(500) DEFAULT NULL, INDEX IDX_F457D0DAE280E2E0 (description_question_choix_hebergement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_choix_restaurant (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_68C53F25A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_choix_restaurant_detail (id INT AUTO_INCREMENT NOT NULL, description_question_choix_restaurant_id INT NOT NULL, designation VARCHAR(255) NOT NULL, reponse VARCHAR(500) DEFAULT NULL, INDEX IDX_60FB8314EB175D50 (description_question_choix_restaurant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_hebergement (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_4E0F4419A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_hebergement_detail (id INT AUTO_INCREMENT NOT NULL, description_question_hebergement_id INT NOT NULL, designation VARCHAR(255) NOT NULL, reponse VARCHAR(500) DEFAULT NULL, INDEX IDX_4821B1A8711CCA11 (description_question_hebergement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_restaurant (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_B9887AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_question_restaurant_detail (id INT AUTO_INCREMENT NOT NULL, description_question_restaurant_id INT NOT NULL, designation VARCHAR(255) NOT NULL, reponse VARCHAR(500) DEFAULT NULL, INDEX IDX_7019EBA57EC031DD (description_question_restaurant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_restaurant (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_5479C5FEA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_restaurant_detail (id INT AUTO_INCREMENT NOT NULL, description_restaurant_id INT NOT NULL, designation VARCHAR(255) NOT NULL, superficie VARCHAR(255) DEFAULT NULL, nombre INT DEFAULT NULL, INDEX IDX_12FC4CD8464F712D (description_restaurant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE description_type_de_demande (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, modele LONGTEXT NOT NULL, INDEX IDX_ABDCECFBA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE designation_camping (id INT AUTO_INCREMENT NOT NULL, designation VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE designation_construction (id INT AUTO_INCREMENT NOT NULL, designation VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE designation_equipement_restaurant (id INT AUTO_INCREMENT NOT NULL, designation VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE designation_hebergement (id INT AUTO_INCREMENT NOT NULL, designation VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE designation_reference (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, reference VARCHAR(255) NOT NULL, datesignature DATETIME NOT NULL, signataire VARCHAR(255) NOT NULL, INDEX IDX_630F928CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE designation_restaurant (id INT AUTO_INCREMENT NOT NULL, designation VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE designation_type_model (id INT AUTO_INCREMENT NOT NULL, designation LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE district (id INT AUTO_INCREMENT NOT NULL, region_id INT NOT NULL, name VARCHAR(100) NOT NULL, INDEX IDX_31C1548798260155 (region_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, filename VARCHAR(255) NOT NULL, pdf_data LONGBLOB NOT NULL, is_processed TINYINT(1) NOT NULL, INDEX IDX_D8698A76A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dossier_ao (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, lettre_demande LONGBLOB DEFAULT NULL, cnaps LONGBLOB DEFAULT NULL, copie_visa_certifie LONGBLOB DEFAULT NULL, attestation_assurance LONGBLOB DEFAULT NULL, attestation_financiere LONGBLOB DEFAULT NULL, INDEX IDX_3E175FD6A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enregistrement_de_ma_demande (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, date DATE NOT NULL, typedemande VARCHAR(255) NOT NULL, INDEX IDX_6AA3CF79A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE environnement (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, nom_site VARCHAR(255) NOT NULL, distance VARCHAR(255) NOT NULL, est VARCHAR(255) NOT NULL, observation VARCHAR(255) NOT NULL, INDEX IDX_A2D30A21A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fokotany (id INT AUTO_INCREMENT NOT NULL, commune_id INT NOT NULL, name VARCHAR(100) NOT NULL, INDEX IDX_8E64C31131A4F72 (commune_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_activite (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, activite VARCHAR(255) NOT NULL, INDEX IDX_29D75E65A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_activite1 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lieu_implantation (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, adresse VARCHAR(255) NOT NULL, commune VARCHAR(255) NOT NULL, district VARCHAR(255) NOT NULL, region VARCHAR(255) NOT NULL, fokotany VARCHAR(255) NOT NULL, INDEX IDX_801F89D5A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ma_demande (id INT AUTO_INCREMENT NOT NULL, id_cas_de_location_id INT DEFAULT NULL, id_categorie_classement_id INT DEFAULT NULL, id_lieu_implantation_id INT DEFAULT NULL, id_nature_ouvrage_id INT DEFAULT NULL, id_nature_projet_id INT DEFAULT NULL, id_plan_masse_id INT DEFAULT NULL, id_relation_activite_id INT DEFAULT NULL, id_users_id INT NOT NULL, id_renseignement_entreprise_id INT DEFAULT NULL, id_renseignement_entreprises_id INT DEFAULT NULL, id_resneignement_individuelle_id INT DEFAULT NULL, id_renseignement_cin_id INT DEFAULT NULL, id_renseignement_visa_id INT DEFAULT NULL, id_environnement_id INT DEFAULT NULL, id_type_construction_id INT DEFAULT NULL, date_actuel DATETIME NOT NULL, ma_type_de_demande VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, INDEX IDX_BB759BE09400E8B9 (id_cas_de_location_id), INDEX IDX_BB759BE0C8B79024 (id_categorie_classement_id), INDEX IDX_BB759BE086BAED38 (id_lieu_implantation_id), INDEX IDX_BB759BE08915F35 (id_nature_ouvrage_id), INDEX IDX_BB759BE0FE0A6662 (id_nature_projet_id), INDEX IDX_BB759BE0157C352E (id_plan_masse_id), INDEX IDX_BB759BE0F37EC10F (id_relation_activite_id), INDEX IDX_BB759BE0376858A8 (id_users_id), INDEX IDX_BB759BE018BDFEB5 (id_renseignement_entreprise_id), INDEX IDX_BB759BE05C6247D8 (id_renseignement_entreprises_id), INDEX IDX_BB759BE0EE366F45 (id_resneignement_individuelle_id), INDEX IDX_BB759BE0DD5449E4 (id_renseignement_cin_id), INDEX IDX_BB759BE0174DB043 (id_renseignement_visa_id), INDEX IDX_BB759BE05971D770 (id_environnement_id), INDEX IDX_BB759BE0348C74AA (id_type_construction_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nationalite (id INT AUTO_INCREMENT NOT NULL, nom_nationalite VARCHAR(255) NOT NULL, code_nationalite VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nature_ouvrage (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, nature VARCHAR(255) NOT NULL, INDEX IDX_4A2B800DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nature_projet (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, nature VARCHAR(255) NOT NULL, INDEX IDX_64193E7EA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE plan_masse (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, plan_masse LONGBLOB DEFAULT NULL, plan_esquisse LONGBLOB DEFAULT NULL, plan_immatriculation LONGBLOB DEFAULT NULL, plan_assainissement LONGBLOB DEFAULT NULL, certificat_situation_juridique_terrain LONGBLOB DEFAULT NULL, INDEX IDX_18C1F890A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE question_camping (id INT AUTO_INCREMENT NOT NULL, questions VARCHAR(500) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE question_choix_camping (id INT AUTO_INCREMENT NOT NULL, questions VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE question_choix_hebergement (id INT AUTO_INCREMENT NOT NULL, questions VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE question_choix_restaurant (id INT AUTO_INCREMENT NOT NULL, questions VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE question_hebergement (id INT AUTO_INCREMENT NOT NULL, questions VARCHAR(500) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE question_restaurant (id INT AUTO_INCREMENT NOT NULL, questions VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE region (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE relation_activite (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, nom_groupe VARCHAR(255) NOT NULL, nom_activite VARCHAR(255) NOT NULL, INDEX IDX_9F6E6FADA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE renseignement_cin (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, num_cin VARCHAR(255) NOT NULL, date_cin DATE NOT NULL, lieu_cin VARCHAR(255) NOT NULL, duplicata_cin VARCHAR(255) NOT NULL, lieu_duplicata_cin VARCHAR(255) NOT NULL, profession VARCHAR(255) NOT NULL, nom_pere VARCHAR(255) NOT NULL, nom_mere VARCHAR(255) NOT NULL, INDEX IDX_6E2870E6A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE renseignement_entreprise (id INT AUTO_INCREMENT NOT NULL, nationalite_id INT NOT NULL, user_id INT NOT NULL, denomination_sociale VARCHAR(255) NOT NULL, enseigne_commerciale VARCHAR(255) DEFAULT NULL, adresse_entreprise VARCHAR(255) NOT NULL, registre_commerce VARCHAR(255) NOT NULL, telephone_entreprise VARCHAR(15) NOT NULL, mail_entreprise VARCHAR(255) NOT NULL, nom_mandataire VARCHAR(255) NOT NULL, prenom_mandataire VARCHAR(255) NOT NULL, INDEX IDX_3D940D741B063272 (nationalite_id), INDEX IDX_3D940D74A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE renseignement_individuelle (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, nationalite_id INT NOT NULL, individu_nom VARCHAR(255) NOT NULL, individu_prenom VARCHAR(255) NOT NULL, adresse_individu VARCHAR(255) NOT NULL, mail_individu VARCHAR(255) NOT NULL, phone_individu VARCHAR(20) NOT NULL, error LONGTEXT DEFAULT NULL, INDEX IDX_86D40981A76ED395 (user_id), INDEX IDX_86D409811B063272 (nationalite_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE renseignement_responsable (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, responsable VARCHAR(255) NOT NULL, INDEX IDX_48B8548DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE renseignement_type_entreprise (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, type_entrprise VARCHAR(255) NOT NULL, INDEX IDX_A8608D39A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE renseignement_visa (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, num_passeport VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, nom_passeport VARCHAR(255) NOT NULL, prenom_passeport VARCHAR(255) NOT NULL, date_naissance DATE NOT NULL, nationalite VARCHAR(255) NOT NULL, date_delivrance DATE NOT NULL, validite DATE NOT NULL, categorie VARCHAR(255) NOT NULL, INDEX IDX_391B1ACFA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE responsable_demande (id INT AUTO_INCREMENT NOT NULL, ma_demande_id INT NOT NULL, drtm TINYINT(1) NOT NULL, edbm TINYINT(1) NOT NULL, dat TINYINT(1) NOT NULL, dg TINYINT(1) NOT NULL, sg TINYINT(1) NOT NULL, ministre TINYINT(1) NOT NULL, INDEX IDX_3A5B6B567D79C349 (ma_demande_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE resultat_demande (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, id_demande_id INT NOT NULL, reference VARCHAR(255) NOT NULL, INDEX IDX_33266B90A76ED395 (user_id), INDEX IDX_33266B902563DECF (id_demande_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_activite (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, nature_activite JSON NOT NULL, INDEX IDX_758A72E9A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_construction (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, INDEX IDX_5BD2586BA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_construction_detail (id INT AUTO_INCREMENT NOT NULL, type_construction_id INT NOT NULL, designation VARCHAR(255) NOT NULL, unite VARCHAR(255) DEFAULT NULL, nombre INT DEFAULT NULL, INDEX IDX_5160AE0F387C850E (type_construction_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_etablissement (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, nature JSON NOT NULL, INDEX IDX_5010EE19A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE upload_avis_ouverture (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, judiciaire LONGBLOB DEFAULT NULL, cin LONGBLOB DEFAULT NULL, visa LONGBLOB DEFAULT NULL, statuts LONGBLOB DEFAULT NULL, assurance LONGBLOB DEFAULT NULL, financiere LONGBLOB DEFAULT NULL, certificat_juridique LONGBLOB DEFAULT NULL, INDEX IDX_4653877FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, prenoms VARCHAR(255) NOT NULL, region VARCHAR(255) NOT NULL, pays VARCHAR(255) NOT NULL, codepostal VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, entreprise VARCHAR(255) NOT NULL, ville VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, is_verified TINYINT(1) NOT NULL, verification_token VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE activite1 ADD CONSTRAINT FK_EEB97E0916C293C5 FOREIGN KEY (groupe_activite1_id) REFERENCES groupe_activite1 (id)');
        $this->addSql('ALTER TABLE cas_de_location ADD CONSTRAINT FK_9D07659EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE categorie_classement ADD CONSTRAINT FK_CB2757C1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE commune ADD CONSTRAINT FK_E2E2D1EEB08FA272 FOREIGN KEY (district_id) REFERENCES district (id)');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_camping ADD CONSTRAINT FK_62841159A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_camping_detail ADD CONSTRAINT FK_7CBBCC90BC20B444 FOREIGN KEY (description_camping_id) REFERENCES description_camping (id)');
        $this->addSql('ALTER TABLE description_equipement_restaurant ADD CONSTRAINT FK_F3FB103BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_equipement_restaurant_detail ADD CONSTRAINT FK_D5B0B326464F712D FOREIGN KEY (description_restaurant_id) REFERENCES description_equipement_restaurant (id)');
        $this->addSql('ALTER TABLE description_hebergement ADD CONSTRAINT FK_A48EC36DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_hebergement_detail ADD CONSTRAINT FK_66F7598ECC99B74D FOREIGN KEY (description_hebergement_id) REFERENCES description_hebergement (id)');
        $this->addSql('ALTER TABLE description_question_camping ADD CONSTRAINT FK_3CBFF80CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_question_camping_detail ADD CONSTRAINT FK_C13EB1CCE8E0F9C0 FOREIGN KEY (description_question_camping_id) REFERENCES description_question_camping (id)');
        $this->addSql('ALTER TABLE description_question_choix_camping ADD CONSTRAINT FK_6852BD2EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_question_choix_camping_detail ADD CONSTRAINT FK_52A2993D809C4E9F FOREIGN KEY (description_question_choix_camping_id) REFERENCES description_question_choix_camping (id)');
        $this->addSql('ALTER TABLE description_question_choix_hebergement ADD CONSTRAINT FK_B5B374CBA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_question_choix_hebergement_detail ADD CONSTRAINT FK_F457D0DAE280E2E0 FOREIGN KEY (description_question_choix_hebergement_id) REFERENCES description_question_choix_hebergement (id)');
        $this->addSql('ALTER TABLE description_question_choix_restaurant ADD CONSTRAINT FK_68C53F25A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_question_choix_restaurant_detail ADD CONSTRAINT FK_60FB8314EB175D50 FOREIGN KEY (description_question_choix_restaurant_id) REFERENCES description_question_choix_restaurant (id)');
        $this->addSql('ALTER TABLE description_question_hebergement ADD CONSTRAINT FK_4E0F4419A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_question_hebergement_detail ADD CONSTRAINT FK_4821B1A8711CCA11 FOREIGN KEY (description_question_hebergement_id) REFERENCES description_question_hebergement (id)');
        $this->addSql('ALTER TABLE description_question_restaurant ADD CONSTRAINT FK_B9887AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_question_restaurant_detail ADD CONSTRAINT FK_7019EBA57EC031DD FOREIGN KEY (description_question_restaurant_id) REFERENCES description_question_restaurant (id)');
        $this->addSql('ALTER TABLE description_restaurant ADD CONSTRAINT FK_5479C5FEA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE description_restaurant_detail ADD CONSTRAINT FK_12FC4CD8464F712D FOREIGN KEY (description_restaurant_id) REFERENCES description_restaurant (id)');
        $this->addSql('ALTER TABLE description_type_de_demande ADD CONSTRAINT FK_ABDCECFBA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE designation_reference ADD CONSTRAINT FK_630F928CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE district ADD CONSTRAINT FK_31C1548798260155 FOREIGN KEY (region_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE dossier_ao ADD CONSTRAINT FK_3E175FD6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE enregistrement_de_ma_demande ADD CONSTRAINT FK_6AA3CF79A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE environnement ADD CONSTRAINT FK_A2D30A21A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE fokotany ADD CONSTRAINT FK_8E64C31131A4F72 FOREIGN KEY (commune_id) REFERENCES commune (id)');
        $this->addSql('ALTER TABLE groupe_activite ADD CONSTRAINT FK_29D75E65A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE lieu_implantation ADD CONSTRAINT FK_801F89D5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE09400E8B9 FOREIGN KEY (id_cas_de_location_id) REFERENCES cas_de_location (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE0C8B79024 FOREIGN KEY (id_categorie_classement_id) REFERENCES categorie_classement (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE086BAED38 FOREIGN KEY (id_lieu_implantation_id) REFERENCES lieu_implantation (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE08915F35 FOREIGN KEY (id_nature_ouvrage_id) REFERENCES nature_ouvrage (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE0FE0A6662 FOREIGN KEY (id_nature_projet_id) REFERENCES nature_projet (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE0157C352E FOREIGN KEY (id_plan_masse_id) REFERENCES plan_masse (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE0F37EC10F FOREIGN KEY (id_relation_activite_id) REFERENCES relation_activite (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE0376858A8 FOREIGN KEY (id_users_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE018BDFEB5 FOREIGN KEY (id_renseignement_entreprise_id) REFERENCES renseignement_type_entreprise (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE05C6247D8 FOREIGN KEY (id_renseignement_entreprises_id) REFERENCES renseignement_entreprise (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE0EE366F45 FOREIGN KEY (id_resneignement_individuelle_id) REFERENCES renseignement_individuelle (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE0DD5449E4 FOREIGN KEY (id_renseignement_cin_id) REFERENCES renseignement_cin (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE0174DB043 FOREIGN KEY (id_renseignement_visa_id) REFERENCES renseignement_visa (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE05971D770 FOREIGN KEY (id_environnement_id) REFERENCES environnement (id)');
        $this->addSql('ALTER TABLE ma_demande ADD CONSTRAINT FK_BB759BE0348C74AA FOREIGN KEY (id_type_construction_id) REFERENCES type_construction (id)');
        $this->addSql('ALTER TABLE nature_ouvrage ADD CONSTRAINT FK_4A2B800DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE nature_projet ADD CONSTRAINT FK_64193E7EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE plan_masse ADD CONSTRAINT FK_18C1F890A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE relation_activite ADD CONSTRAINT FK_9F6E6FADA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE renseignement_cin ADD CONSTRAINT FK_6E2870E6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE renseignement_entreprise ADD CONSTRAINT FK_3D940D741B063272 FOREIGN KEY (nationalite_id) REFERENCES nationalite (id)');
        $this->addSql('ALTER TABLE renseignement_entreprise ADD CONSTRAINT FK_3D940D74A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE renseignement_individuelle ADD CONSTRAINT FK_86D40981A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE renseignement_individuelle ADD CONSTRAINT FK_86D409811B063272 FOREIGN KEY (nationalite_id) REFERENCES nationalite (id)');
        $this->addSql('ALTER TABLE renseignement_responsable ADD CONSTRAINT FK_48B8548DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE renseignement_type_entreprise ADD CONSTRAINT FK_A8608D39A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE renseignement_visa ADD CONSTRAINT FK_391B1ACFA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE responsable_demande ADD CONSTRAINT FK_3A5B6B567D79C349 FOREIGN KEY (ma_demande_id) REFERENCES ma_demande (id)');
        $this->addSql('ALTER TABLE resultat_demande ADD CONSTRAINT FK_33266B90A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE resultat_demande ADD CONSTRAINT FK_33266B902563DECF FOREIGN KEY (id_demande_id) REFERENCES resultat_demande (id)');
        $this->addSql('ALTER TABLE type_activite ADD CONSTRAINT FK_758A72E9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE type_construction ADD CONSTRAINT FK_5BD2586BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE type_construction_detail ADD CONSTRAINT FK_5160AE0F387C850E FOREIGN KEY (type_construction_id) REFERENCES type_construction (id)');
        $this->addSql('ALTER TABLE type_etablissement ADD CONSTRAINT FK_5010EE19A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE upload_avis_ouverture ADD CONSTRAINT FK_4653877FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activite1 DROP FOREIGN KEY FK_EEB97E0916C293C5');
        $this->addSql('ALTER TABLE cas_de_location DROP FOREIGN KEY FK_9D07659EA76ED395');
        $this->addSql('ALTER TABLE categorie_classement DROP FOREIGN KEY FK_CB2757C1A76ED395');
        $this->addSql('ALTER TABLE commune DROP FOREIGN KEY FK_E2E2D1EEB08FA272');
        $this->addSql('ALTER TABLE demande DROP FOREIGN KEY FK_2694D7A5A76ED395');
        $this->addSql('ALTER TABLE description_camping DROP FOREIGN KEY FK_62841159A76ED395');
        $this->addSql('ALTER TABLE description_camping_detail DROP FOREIGN KEY FK_7CBBCC90BC20B444');
        $this->addSql('ALTER TABLE description_equipement_restaurant DROP FOREIGN KEY FK_F3FB103BA76ED395');
        $this->addSql('ALTER TABLE description_equipement_restaurant_detail DROP FOREIGN KEY FK_D5B0B326464F712D');
        $this->addSql('ALTER TABLE description_hebergement DROP FOREIGN KEY FK_A48EC36DA76ED395');
        $this->addSql('ALTER TABLE description_hebergement_detail DROP FOREIGN KEY FK_66F7598ECC99B74D');
        $this->addSql('ALTER TABLE description_question_camping DROP FOREIGN KEY FK_3CBFF80CA76ED395');
        $this->addSql('ALTER TABLE description_question_camping_detail DROP FOREIGN KEY FK_C13EB1CCE8E0F9C0');
        $this->addSql('ALTER TABLE description_question_choix_camping DROP FOREIGN KEY FK_6852BD2EA76ED395');
        $this->addSql('ALTER TABLE description_question_choix_camping_detail DROP FOREIGN KEY FK_52A2993D809C4E9F');
        $this->addSql('ALTER TABLE description_question_choix_hebergement DROP FOREIGN KEY FK_B5B374CBA76ED395');
        $this->addSql('ALTER TABLE description_question_choix_hebergement_detail DROP FOREIGN KEY FK_F457D0DAE280E2E0');
        $this->addSql('ALTER TABLE description_question_choix_restaurant DROP FOREIGN KEY FK_68C53F25A76ED395');
        $this->addSql('ALTER TABLE description_question_choix_restaurant_detail DROP FOREIGN KEY FK_60FB8314EB175D50');
        $this->addSql('ALTER TABLE description_question_hebergement DROP FOREIGN KEY FK_4E0F4419A76ED395');
        $this->addSql('ALTER TABLE description_question_hebergement_detail DROP FOREIGN KEY FK_4821B1A8711CCA11');
        $this->addSql('ALTER TABLE description_question_restaurant DROP FOREIGN KEY FK_B9887AA76ED395');
        $this->addSql('ALTER TABLE description_question_restaurant_detail DROP FOREIGN KEY FK_7019EBA57EC031DD');
        $this->addSql('ALTER TABLE description_restaurant DROP FOREIGN KEY FK_5479C5FEA76ED395');
        $this->addSql('ALTER TABLE description_restaurant_detail DROP FOREIGN KEY FK_12FC4CD8464F712D');
        $this->addSql('ALTER TABLE description_type_de_demande DROP FOREIGN KEY FK_ABDCECFBA76ED395');
        $this->addSql('ALTER TABLE designation_reference DROP FOREIGN KEY FK_630F928CA76ED395');
        $this->addSql('ALTER TABLE district DROP FOREIGN KEY FK_31C1548798260155');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76A76ED395');
        $this->addSql('ALTER TABLE dossier_ao DROP FOREIGN KEY FK_3E175FD6A76ED395');
        $this->addSql('ALTER TABLE enregistrement_de_ma_demande DROP FOREIGN KEY FK_6AA3CF79A76ED395');
        $this->addSql('ALTER TABLE environnement DROP FOREIGN KEY FK_A2D30A21A76ED395');
        $this->addSql('ALTER TABLE fokotany DROP FOREIGN KEY FK_8E64C31131A4F72');
        $this->addSql('ALTER TABLE groupe_activite DROP FOREIGN KEY FK_29D75E65A76ED395');
        $this->addSql('ALTER TABLE lieu_implantation DROP FOREIGN KEY FK_801F89D5A76ED395');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE09400E8B9');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE0C8B79024');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE086BAED38');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE08915F35');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE0FE0A6662');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE0157C352E');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE0F37EC10F');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE0376858A8');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE018BDFEB5');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE05C6247D8');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE0EE366F45');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE0DD5449E4');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE0174DB043');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE05971D770');
        $this->addSql('ALTER TABLE ma_demande DROP FOREIGN KEY FK_BB759BE0348C74AA');
        $this->addSql('ALTER TABLE nature_ouvrage DROP FOREIGN KEY FK_4A2B800DA76ED395');
        $this->addSql('ALTER TABLE nature_projet DROP FOREIGN KEY FK_64193E7EA76ED395');
        $this->addSql('ALTER TABLE plan_masse DROP FOREIGN KEY FK_18C1F890A76ED395');
        $this->addSql('ALTER TABLE relation_activite DROP FOREIGN KEY FK_9F6E6FADA76ED395');
        $this->addSql('ALTER TABLE renseignement_cin DROP FOREIGN KEY FK_6E2870E6A76ED395');
        $this->addSql('ALTER TABLE renseignement_entreprise DROP FOREIGN KEY FK_3D940D741B063272');
        $this->addSql('ALTER TABLE renseignement_entreprise DROP FOREIGN KEY FK_3D940D74A76ED395');
        $this->addSql('ALTER TABLE renseignement_individuelle DROP FOREIGN KEY FK_86D40981A76ED395');
        $this->addSql('ALTER TABLE renseignement_individuelle DROP FOREIGN KEY FK_86D409811B063272');
        $this->addSql('ALTER TABLE renseignement_responsable DROP FOREIGN KEY FK_48B8548DA76ED395');
        $this->addSql('ALTER TABLE renseignement_type_entreprise DROP FOREIGN KEY FK_A8608D39A76ED395');
        $this->addSql('ALTER TABLE renseignement_visa DROP FOREIGN KEY FK_391B1ACFA76ED395');
        $this->addSql('ALTER TABLE responsable_demande DROP FOREIGN KEY FK_3A5B6B567D79C349');
        $this->addSql('ALTER TABLE resultat_demande DROP FOREIGN KEY FK_33266B90A76ED395');
        $this->addSql('ALTER TABLE resultat_demande DROP FOREIGN KEY FK_33266B902563DECF');
        $this->addSql('ALTER TABLE type_activite DROP FOREIGN KEY FK_758A72E9A76ED395');
        $this->addSql('ALTER TABLE type_construction DROP FOREIGN KEY FK_5BD2586BA76ED395');
        $this->addSql('ALTER TABLE type_construction_detail DROP FOREIGN KEY FK_5160AE0F387C850E');
        $this->addSql('ALTER TABLE type_etablissement DROP FOREIGN KEY FK_5010EE19A76ED395');
        $this->addSql('ALTER TABLE upload_avis_ouverture DROP FOREIGN KEY FK_4653877FA76ED395');
        $this->addSql('DROP TABLE activite1');
        $this->addSql('DROP TABLE `admin`');
        $this->addSql('DROP TABLE apropos');
        $this->addSql('DROP TABLE cas_de_location');
        $this->addSql('DROP TABLE categorie_classement');
        $this->addSql('DROP TABLE commune');
        $this->addSql('DROP TABLE demande');
        $this->addSql('DROP TABLE description_camping');
        $this->addSql('DROP TABLE description_camping_detail');
        $this->addSql('DROP TABLE description_equipement_restaurant');
        $this->addSql('DROP TABLE description_equipement_restaurant_detail');
        $this->addSql('DROP TABLE description_hebergement');
        $this->addSql('DROP TABLE description_hebergement_detail');
        $this->addSql('DROP TABLE description_question_camping');
        $this->addSql('DROP TABLE description_question_camping_detail');
        $this->addSql('DROP TABLE description_question_choix_camping');
        $this->addSql('DROP TABLE description_question_choix_camping_detail');
        $this->addSql('DROP TABLE description_question_choix_hebergement');
        $this->addSql('DROP TABLE description_question_choix_hebergement_detail');
        $this->addSql('DROP TABLE description_question_choix_restaurant');
        $this->addSql('DROP TABLE description_question_choix_restaurant_detail');
        $this->addSql('DROP TABLE description_question_hebergement');
        $this->addSql('DROP TABLE description_question_hebergement_detail');
        $this->addSql('DROP TABLE description_question_restaurant');
        $this->addSql('DROP TABLE description_question_restaurant_detail');
        $this->addSql('DROP TABLE description_restaurant');
        $this->addSql('DROP TABLE description_restaurant_detail');
        $this->addSql('DROP TABLE description_type_de_demande');
        $this->addSql('DROP TABLE designation_camping');
        $this->addSql('DROP TABLE designation_construction');
        $this->addSql('DROP TABLE designation_equipement_restaurant');
        $this->addSql('DROP TABLE designation_hebergement');
        $this->addSql('DROP TABLE designation_reference');
        $this->addSql('DROP TABLE designation_restaurant');
        $this->addSql('DROP TABLE designation_type_model');
        $this->addSql('DROP TABLE district');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE dossier_ao');
        $this->addSql('DROP TABLE enregistrement_de_ma_demande');
        $this->addSql('DROP TABLE environnement');
        $this->addSql('DROP TABLE fokotany');
        $this->addSql('DROP TABLE groupe_activite');
        $this->addSql('DROP TABLE groupe_activite1');
        $this->addSql('DROP TABLE lieu_implantation');
        $this->addSql('DROP TABLE ma_demande');
        $this->addSql('DROP TABLE nationalite');
        $this->addSql('DROP TABLE nature_ouvrage');
        $this->addSql('DROP TABLE nature_projet');
        $this->addSql('DROP TABLE plan_masse');
        $this->addSql('DROP TABLE question_camping');
        $this->addSql('DROP TABLE question_choix_camping');
        $this->addSql('DROP TABLE question_choix_hebergement');
        $this->addSql('DROP TABLE question_choix_restaurant');
        $this->addSql('DROP TABLE question_hebergement');
        $this->addSql('DROP TABLE question_restaurant');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE relation_activite');
        $this->addSql('DROP TABLE renseignement_cin');
        $this->addSql('DROP TABLE renseignement_entreprise');
        $this->addSql('DROP TABLE renseignement_individuelle');
        $this->addSql('DROP TABLE renseignement_responsable');
        $this->addSql('DROP TABLE renseignement_type_entreprise');
        $this->addSql('DROP TABLE renseignement_visa');
        $this->addSql('DROP TABLE responsable_demande');
        $this->addSql('DROP TABLE resultat_demande');
        $this->addSql('DROP TABLE type_activite');
        $this->addSql('DROP TABLE type_construction');
        $this->addSql('DROP TABLE type_construction_detail');
        $this->addSql('DROP TABLE type_etablissement');
        $this->addSql('DROP TABLE upload_avis_ouverture');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
